"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os # Imported for environment variable access
import dj_database_url # Imported for parsing Heroku database URL
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable for SECRET_KEY in production for security
SECRET_KEY = os.environ.get('SECRET_KEY', 'your-fallback-secret-key-for-development-only') # Replace with your actual development key

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG is True only if 'DEBUG' environment variable is set
DEBUG = 'DEBUG' in os.environ

# ALLOWED_HOSTS for production deployment
# Replace 'your-heroku-app-name.herokuapp.com' with your actual Heroku app name
ALLOWED_HOSTS = ['the-cameroonian-table-app-38cd3afcabf7.herokuapp.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # NEW: Added django.contrib.sites for allauth
    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dishes', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Added WhiteNoise middleware for serving static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'allauth.account.middleware.AccountMiddleware', # Allauth Account Middleware - Commented out for testing
]



ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Django will now look for templates here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use dj_database_url to parse the DATABASE_URL environment variable from Heroku
DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3', conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
# HIER WURDE STATICFILES_DIRS HINZUGEFÜGT:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Dies ist für projektweite statische Dateien
]
# STATIC_ROOT: The absolute path to the directory where collectstatic will gather static files for deployment.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (for user-uploaded content like images)
# MEDIA_URL: The URL that will handle media served from MEDIA_ROOT.
MEDIA_URL = '/media/'
# MEDIA_ROOT: The absolute filesystem path to the directory that will hold user-uploaded files.
MEDIA_ROOT = BASE_DIR / 'media'


# Allauth settings - UPDATED FOR DEPRECATED WARNINGS
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1 # Required by allauth

# Allauth specific settings - UPDATED
ACCOUNT_LOGIN_METHODS = ['username', 'email'] # Replaces ACCOUNT_AUTHENTICATION_METHOD
ACCOUNT_EMAIL_VERIFICATION = 'none' # 'mandatory' for email verification, 'none' for no verification

# New way to configure signup fields, replaces ACCOUNT_EMAIL_REQUIRED, ACCOUNT_USERNAME_REQUIRED, ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE
# The warning suggests this format to explicitly mark fields as required
ACCOUNT_SIGNUP_FIELDS = ['username', 'email*', 'email2*'] 

# New way to configure rate limits, replaces ACCOUNT_LOGIN_ATTEMPTS_LIMIT/TIMEOUT
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m' # 5 failed login attempts within 5 minutes
}

ACCOUNT_LOGOUT_REDIRECT_URL = '/' # Redirect to homepage after logout
LOGIN_REDIRECT_URL = '/' # Redirect to homepage after successful login


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
